version: "3.9"

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.22
    ports:
      - "8001:8001"
    volumes:
      - ./django_backend/chroma_store:/chroma/chroma
    entrypoint: uvicorn chromadb.app:app --host 0.0.0.0 --port 8001 --proxy-headers

  embedding_service:
    build:
      context: ./django_backend/embedding_service
    ports:
      - "9001:9001"

