# Generated by Django 5.2.1 on 2025-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0002_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(help_text='LLM system prompt for this company category (shown in chatbot prompt).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
