# Generated by Django 5.2.1 on 2025-05-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0003_companycategory_alter_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='api_gateway.companycategory'),
        ),
    ]
