# Generated by Django 5.2.1 on 2025-05-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gateway', '0004_tenant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='instructions',
            field=models.TextField(blank=True, help_text='(Optional) Custom LLM prompt instructions for this tenant. If blank, falls back to category instructions.'),
        ),
    ]
